### ISSUE TITLE
React Native support

### ISSUE THREAD

**Issue by Jempan** [kiwicom/orbit-components#1002]
Hi! 

I am looking for a styling framework built with styled components which supports both web and react native. Found your components today and they look great! I can see that your RN-branch havn't been touched for half a year, is a release with RN support still on your roadmap?

Many thanks!

**Comment by honzatmn** [comment]
Hi Jenny, it’s great that you like Orbit!:) 

We are still very experimental with RN, but check our other repo for RN components: https://github.com/kiwicom/margarita/tree/master/packages/universal-components

We are currently reviewing design and implementation, but, eventually, we plan to have all Orbit components in RN too.
