### ISSUE TITLE
<CardSection expandable>: unshifting an array of expanded card sections

### ISSUE THREAD

**Issue by Radek-Palisa** [kiwicom/orbit-components#1005]
## Expected Behavior

When I add dynamically expandable card sections, I expect consistent behaviour: either all cards get closed or the cards that had been opened will stay open while newly added cards will be closed.

## Current Behavior

If i have a card section expanded and then dynamically add another item before it, the newly added item will get expanded while the previous item gets closed. Moreover, although the card section is expanded, the card section body remains hidden. Check "steps to reproduce".

## Steps to Reproduce

https://codesandbox.io/embed/l5xyy0zy9

**Comment by vepor** [comment]
Fixed in #1382 . Release in version **0.69.0**.
