### ISSUE TITLE
<Modal>: textless close button should include aria-label

### ISSUE THREAD

**Issue by Radek-Palisa** [kiwicom/orbit-components#1014]
**Is your feature request related to a problem? Please describe.**
If a button element consist of only icon, we should include an aria-label on it

**Describe the solution you'd like**
Either include it internally or expose a prop to accept translation.

**Comment by honzatmn** [comment]
Hi, thanks for reporting it. We are currently working on integrating simple strings like this into Orbit (with translations), this will be covered by it too.

**Comment by vepor** [comment]
Title of close Button inside Modal component added in #1062
