### ISSUE TITLE
Unit test Checkbox

### ISSUE THREAD

**Issue by VaclavSir** [kiwicom/orbit-components#108]
Test that:
- It renders without crashing
- It calls the callback when clicked the input
- It calls the callback when clicked the label

---
Make sure these boxes are ticked before submitting a new issue:

* [x] I have checked that this is not a duplicate
* [x] I have added a label categorizing this under BLKN | Kiwicom | Icons | Global

**Comment by wEprous** [comment]
Fixed in #150
