### ISSUE TITLE
Configure react/jsx-no-bind properly

### ISSUE THREAD

**Issue by VaclavSir** [kiwicom/orbit-components#109]
The rule `react/jsx-no-bind` doesn't warn us when we use an arrow function as a prop (eg. `<Button onClick={() => {}} />`). It should.

---
Make sure these boxes are ticked before submitting a new issue:

* [x] I have checked that this is not a duplicate
* [x] I have added a label categorizing this under BLKN | Kiwicom | Icons | Global

**Comment by vepor** [comment]
`react/jsx-no-bind` doesn't have to configured properly anymore. Since React version with hooks, binding is considered as normal and safe way. Only makes sense for PureComponent or memoized functional component, that we don't use.
