### ISSUE TITLE
Carrier badge component

### ISSUE THREAD

**Issue by borisvida** [kiwicom/orbit-components#1128]
## Description
Carrier logo in a for of a Notification badge.

## Visual style
![image](https://user-images.githubusercontent.com/6271307/61119951-330f3980-a49c-11e9-802c-93d905e71d4c.png)

Zeplin: 
https://app.zeplin.io/project/5d232cd391be672e1f348f14/screen/5d24789379cc489985cc269b

### Interactions
Same as current CarrierLogo.

### Additional information
There'll always be just one carrier. If there are more carriers for a particular trip, there will be Kiwi.com supercarrier logo shown (we can send some specific value in that case).

## Functional specs
Same as current NotificationBadge (except `children` probably).

**Comment by honzatmn** [comment]
Hi Boris, please use `CarrierLogo` component for it, it shouldn't be placed into a `NotificationBadge` (it's not notification after all, also padding would collide with it).

Keep it with rounded corners, for now, we are preparing logos to be able to put them into circles (it crops them weirdly now). When it's done, it will change globally to circles.
