### ISSUE TITLE
Radio with checked=true causes hasError=true to have no effect

### ISSUE THREAD

**Issue by prztrz** [kiwicom/orbit-components#1134]
error in `Radio` component with props `{hasError: true, checked: true}` is not visible in UI

## Expected Behavior
I would expect to have red border of checked radio to indicate error.

## Current Behavior
If `Radio` is checked there is no error indication

## Steps to Reproduce
1. Go to storybook
2. Go to Radio -> playground
3. Select `checked` and `hasError` knobs

**Comment by vepor** [comment]
As discussed internally a long time ago, this would be against user experience, or, at least, potentially. In terms of `Radio` it doesn't make sense to have it with `hasError` and `checked` together. Hence, closing.
