### ISSUE TITLE
Button breaks with 'Cannot read property 'replace' of undefined'

### ISSUE THREAD

**Issue by LacraDanciu** [kiwicom/orbit-components#1157]
Use this **ONLY** for reporting bugs. For requesting new features check [this link](https://orbit.kiwi/request-an-enhancement/).

## Expected Behavior
Render the buttons and the page

## Current Behavior
it breaks the page, nothing is rendered anymore

## Steps to Reproduce

1.
2.
3.
4.

**Comment by filipdanisko** [comment]
Hey @LacraDanciu, are you using the latest 0.52.0? There was an issue on 0.51 with orbit-token dependency causing this issue to happen

**Comment by LacraDanciu** [comment]
Thanks, this was it. I'll close the issue.
