### ISSUE TITLE
TypeError: Cannot read property 'widthBreakpointMediumMobile' of undefined at getBreakpointWidth

### ISSUE THREAD

**Issue by bidah** [kiwicom/orbit-components#1176]
## Expected Behavior
Import `mediaQuery` and be able to use it with styled components `css` prop.

## Current Behavior
importing works. But when you use `media` on the `css` prop it throws this error:

```
TypeError: Cannot read property 'widthBreakpointMediumMobile' of undefined
    at getBreakpointWidth
```

## Steps to Reproduce
1. `expo start`
2. `npm add styled-components @kiwicom/orbit-components`
3. import on App.js `import media from "@kiwicom/orbit-components/lib/utils/mediaQuery"`
4. add a `css` prop and use the media queries.

## Context (Environment)
I am trying to use MediaQueries for Expo Web

**Comment by vepor** [comment]
If you want to use `mediaQuery` functions in your project, you need to setup `defaultProps` of every `styled component`, that uses it, explicitly.
https://codesandbox.io/s/orbit-sandbox-4kuy7

Other solution is to use `ThemeProvider` and have `theme` object available all the time, everywhere. 
https://github.com/kiwicom/orbit-components/blob/master/.github/theming.md
