### ISSUE TITLE
CountryFlag code defaultProp 'anywhere'

### ISSUE THREAD

**Issue by tbergq** [kiwicom/orbit-components#1189]
When working with grahpql, types are nullable by default. It would be great to have `anywhere` as default prop to CountryFlag. So we don't have to do this every time `<CountryFlag code={location?.country?.code ?? 'anywhere'}` />

**Comment by tbergq** [comment]
Nevermind me, seems this is already implemented.

**Comment by tbergq** [comment]
I am going to reopen this, because `<CountryFlag code={location?.country?.code} />` this gives error

<img width="893" alt="Screenshot 2019-08-24 at 11 03 44" src="https://user-images.githubusercontent.com/7705041/63635102-dee0a300-c65e-11e9-9c1c-ffaeffff796e.png">

**Comment by michalsanger** [comment]
It was merged in #801 so it looks like it was reverted later.

**Comment by vepor** [comment]
Actually, from #801 it was optional property, not nullable. Will be fixed by #1190
