### ISSUE TITLE
Create <CardSection /> component

### ISSUE THREAD

**Issue by darkwindcz** [kiwicom/orbit-components#120]
## Description
Card section create a space for sections and adds necessary paddings and delimiters to them for a clear hierarchy. 

## How it looks
![cartsection](https://user-images.githubusercontent.com/6851247/38565087-b29c0df6-3ce0-11e8-9a50-829ac7a08e9b.png)

## Parameters
_none_

## Visual design & design tokens
```
padding: $paddingCardSection
```

### Additional information
- If there is more then one `<CardSection />`, it should show a **line between sections**. For line style use these tokens: `border-width: $borderWidthSection; border-style: $borderStyleSection; border-color: $borderColorSection`
- The content that should go inside section shouldn't set any padding. Section padding is set globally and content is just displayed inside: 
![cardsection-paddings](https://user-images.githubusercontent.com/6851247/38565288-36a9bab2-3ce1-11e8-8d52-ed0321553a00.png)

**Comment by wEprous** [comment]
added in #180
