### ISSUE TITLE
duplicate style?

### ISSUE THREAD

**Issue by straxico** [kiwicom/orbit-components#1232]
hi
i see this image in orbit storybook
![Capture](https://user-images.githubusercontent.com/6344893/64907748-dcc4ae00-d70b-11e9-8cca-fa180109ba4d.PNG)
when i change a small value of this component like color, all style of this component will duplicate and create new style hash with huge similar value and bit different value like color 

its ok?

**Comment by filipdanisko** [comment]
Hey @straxico yes, IMO that's ok, styled-components doesn't create a granular CSS declaration, so this is expected.
