### ISSUE TITLE
{fixed} in FormFeedback

### ISSUE THREAD

**Issue by straxico** [kiwicom/orbit-components#1239]
hi
`fixed` not define in formfeedback prop
https://github.com/kiwicom/orbit-components/blob/master/src/FormFeedback/index.js.flow

but in ChoiceGroup . pass `fixed` to  formfeedback
https://github.com/kiwicom/orbit-components/blob/master/src/ChoiceGroup/index.js
          `<FormFeedback type="error" fixed>`

and in formfeedback not use it

its ok?

**Comment by vepor** [comment]
Thanks for reporting this @straxico!
It seems that it's just totally unnecessary property that was not catched by `flow`, as the `Props` of `FormFeedback` are not exact types. `fixed` will be deleted. 🙂
