### ISSUE TITLE
Many icons are missing from TTF font

### ISSUE THREAD

**Issue by silvenon** [kiwicom/orbit-components#1243]
## Expected Behavior

Icon font files should include all icons from Orbit.

## Current Behavior

The SVG font includes all icons, but TTF doesn't, so it seems like [svg2ttf](https://github.com/fontello/svg2ttf) doesn't work well in our case and doesn't cover all icons. We can also assume that WOFF2 is missing those as well because we're generating them from the TTF file.

## Possible Solution

Use a package like [webfont](https://www.npmjs.com/package/webfont), it's an all-in-one solution that not only works (I verified), but can also produce WOFF and EOT files, which I recommend, and the script simpler.

What do you think? We use a custom icon font on frontend and we would like to switch to Orbit's.

**Comment by vepor** [comment]
But does `webfont` support custom characters? I believe that tried it months ago, but there was not option to do it. (or maybe I tried something else, I'm not sure know 🤔 )

**Comment by silvenon** [comment]
This issue is incorrect, it does (seem to) include all icons, I was viewing the font wrong.
