### ISSUE TITLE
ButtonLink Component type

### ISSUE THREAD

**Issue by straxico** [kiwicom/orbit-components#1248]
hi 
1:in common dir, define Component type as React.ComponentType

  https://github.com/kiwicom/orbit-components/blob/1239930985adb11c17f3f5eeca7e341d26673449/src/common/common.js.flow#L16

`type React.ComponentType<P = {}> = React.ComponentClass<P, any> | React.FunctionComponent<P>`

2:
in buttenLink prop define component as Component type
https://github.com/kiwicom/orbit-components/blob/1239930985adb11c17f3f5eeca7e341d26673449/src/ButtonLink/index.js.flow#L18

3:
in inputStepper pass `PrefixSuffix`  to `ButtonLink`
https://github.com/kiwicom/orbit-components/blob/1239930985adb11c17f3f5eeca7e341d26673449/src/InputStepper/InputStepperStateless/index.js#L113

4:
but `PrefixSuffix` type is  **styledcomponent** and **not a reactComponent** 
 https://github.com/kiwicom/orbit-components/blob/1239930985adb11c17f3f5eeca7e341d26673449/src/InputStepper/InputStepperStateless/index.js#L14

`PrefixSuffix: StyledComponent<({ type, ...props }: any) => JSX.Element, any, {}, never>`

**Comment by vepor** [comment]
Basically, all `styled` components are normal `react` components. And in the end, `styled-components` are not typed properly, more described here #856.
