### ISSUE TITLE
Buttons are broken in Safari

### ISSUE THREAD

**Issue by Fallion** [kiwicom/orbit-components#130]
Make sure these boxes are ticked before submitting a new issue:

* [x] I have checked that this is not a duplicate

For Safari browsers it's important to override default styling.

See: https://css-tricks.com/almanac/properties/a/appearance/

**Comment by darkwindcz** [comment]
@williamkolmacka If it's possible, remove all default styling, as I mentioned in the specification. Only default styling that should stay is a focused state.

**Comment by williamkolmacka** [comment]
@Fallion Did you see this issue on the Button component which is now on master branch? The new Button component looks alright, so I don't know if it's important to fix it because we will update current Button component soon for the new one.

**Comment by Fallion** [comment]
Closed by #135
