### ISSUE TITLE
Attempts to access this ref will fail. Did you mean to use React.forwardRef, Check the render method of `ModalFooter`

### ISSUE THREAD

**Issue by tbergq** [kiwicom/orbit-components#1344]
I am seeing this error message a lot in the console log.

It happens for usage like

```
 <ModalFooter flex={['0 0 auto', '1 1 100%']}>
        ...
 </ModalFooter>
``` 

removing flex, will remove the error message.

**Comment by vepor** [comment]
Hello @tbergq, can you provide more info or examples, so we can reproduce this error?

**Comment by tbergq** [comment]
Code [here](https://gitlab.skypicker.com/frontend/account/blob/master/apps%2Faccount-web%2Fsrc%2Fsettings%2FSavedTravellersPanel%2Fcomponents%2FEditTravelerContent.js#L69)


![edit traveler](https://user-images.githubusercontent.com/7705041/67401496-86bb1400-f5af-11e9-8e67-e66b2242fc3a.gif)
