### ISSUE TITLE
Button ref has wrong flow-type

### ISSUE THREAD

**Issue by tbergq** [kiwicom/orbit-components#1367]
See the flow-error in action [here](https://gitlab.skypicker.com/frontend/account/merge_requests/441/diffs#diff-content-fa885102a1b757becee21743a4ce56c0952b678a), just uncomment the flow-suppression.

<img width="895" alt="Screenshot 2019-11-11 at 10 16 44" src="https://user-images.githubusercontent.com/7705041/68576314-26144e00-046e-11ea-8030-ad340210ab0c.png">

**Comment by vepor** [comment]
Was this fixed already @mainframev?

**Comment by tbergq** [comment]
Yes, We no longer have this error. Thanks
