### ISSUE TITLE
Tooltip stopPropagation is not enough when tooltip is wrapped by anchor tag

### ISSUE THREAD

**Issue by tbergq** [kiwicom/orbit-components#1392]
Use this **ONLY** for reporting bugs. For requesting new features check [this link](https://orbit.kiwi/request-an-enhancement/).

When having a tooltip inside of an `anchor` tag, clicking on it triggers browsers default event, which is redirecting to the href.

## Expected Behavior
it should prevent default behaviour

## Current Behavior
I got redirected to href

## Possible Solution
add option to preventDefault 

## Steps to Reproduce
[codesandbox](https://codesandbox.io/s/epic-mahavira-shkjg)

## Context (Environment)
Wrapping past trips in account with a link to its MMB page.

**Comment by tbergq** [comment]
Having `role=tooltip` and some `aria-label|aria-described` by would also be nice to improve accessibility

**Comment by filipdanisko** [comment]
Hey @tbergq 
to me this is incorrect usage of a tooltip,  because when using a anchor tag user is expecting to be redirected. Is there any reason why you can't simply do this?
```
<a href="https://www.kiwi.com">
  go to kiwi.com
</a>
<Tooltip content={<div>test</div>} stopPropagation={true}>
  <ButtonLink>Click me to see</ButtonLink>
</Tooltip>
```

Ad accessibility, good catch. I'll make sure to implement this!

**Comment by tbergq** [comment]
<img width="464" alt="Screenshot 2019-12-02 at 15 03 28" src="https://user-images.githubusercontent.com/7705041/69965672-0b854000-1515-11ea-9ec1-b008a731e01f.png">

We have this card, which when it is clicked, it should redirect to MMB page. So IMHO, wrapping this an anchor tag is the correct usage, and no, I cannot put the tooltip below. This tooltip is on the passenger badge and will show the name of the passengers.

**Comment by filipdanisko** [comment]
Good point, will update that, Thanks! :))

**Comment by tbergq** [comment]
> Good point, will update that, Thanks! :))

Thank you 😊
