### ISSUE TITLE
Create <Select /> component

### ISSUE THREAD

**Issue by darkwindcz** [kiwicom/orbit-components#159]
## Description
Select box is a form field that we use when we need from users to select one specific value from pre-defined list of values.

## Visual style
![select](https://user-images.githubusercontent.com/6851247/40679288-a979368e-637a-11e8-9c1e-5e7edc86a28e.png)

Zeplin: https://zpl.io/29Dknke

### Interactions
![select-interactions](https://user-images.githubusercontent.com/6851247/40679298-ad83c366-637a-11e8-85ce-185186f7fe5d.png)

Behavior is same as in InputField, described in issue #153

### Additional information
- Everything inside the select is vertically centered
- Select width is 100%
- Space between flag and value is defined by $spaceSmall
- We agreed that it may be a good idea to use same tokens for visual style as we use for InputField because the look is currently the same (and it’s planned to be the same by design)

## Functional specs
- If the user select some value, the color of label needs to change to a lighter shade (an exact color is defined as a token)
- The opened state is default by a browser, we don’t have any custom styling in this first version 
- Help text should be defined as text with a possibility of React component, as it can have a custom action attached to part of it (for example, click on „Czech Republic“ will select „Czech Republic“ option)

## Storybook chapters
We will have with prefix and without prefix very probably. More will be specified after we know which props we have. For now, start with playground and default. 

## Some inspiration
https://polaris.shopify.com/components/forms/select#navigation
http://designsystem.morningstar.com/components/forms.html#select-dropdown--1
https://www.material-ui.com/#/components/select-field
http://seek-oss.github.io/seek-style-guide/dropdown

**Comment by darkwindcz** [comment]
I am not sure about which tokens to use here, I am thinking about two approaches:

**1) use same tokens as for InputField (with "Input" in the name)**
 [plus] as both components are for forms, they all be visually affected by one set of tokens, so the maintenance should be easier
 [minus] it won't be possible to change the visual look just for select or inputs. However, I don't know if that's needed currently.

**2) use new tokens**
 [plus] we can change only select or input when we decide
 [minus] maintenance can be harder as we will need to keep both sets of tokens in sync visually

**Comment by wEprous** [comment]
Added in #219
