### ISSUE TITLE
Create <CountryFlag /> component

### ISSUE THREAD

**Issue by darkwindcz** [kiwicom/orbit-components#160]
## Description
Simple component for handling country flags.

## Visual style
![flag](https://user-images.githubusercontent.com/6851247/39472182-fca0c7ee-4d47-11e8-89e7-019a05b7777e.png)

## Parameters
Parameter | Values | Default
-- | -- | --
Country | string | _empty_
Code | string | _empty_

## Visual design & design tokens
width: $widthCountryFlag
height: $heightCountryFlag
border-radius: $borderRadiusSmall

### Additional information
- Country name should be used for an alt and title of image
- Component should cover retina displays as well

**Comment by darkwindcz** [comment]
We have flags as square image currently (eg. https://www.kiwi.com/images/flags/spFlag-cz.png), but I don't see much value in that - contrariwise tbh. If we use the square as we are using now, we have no control over the look of the image - it's border-radius, shadow, border, ... If we will have classical rectangle country flags, it will allow us to change it more effectively with code and not to re-render all flags images when we decide to change the shape of the flag. Let's discuss this please before someone starts

**Comment by wEprous** [comment]
@williamkolmacka is still choosing some flags
Plz, don't forget to add chapter in Select stories (as prefix)
