### ISSUE TITLE
"url" prop for TextLink needs to be optional

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/orbit-components#181]
Most of the time, all login is handled by `onClick` in react apps and url isn't relevant

**Comment by tomashapl** [comment]
Yes, but TextLink renders 

```
<a />
```

if you want to use link that handles onClick just use `<ButtonLink />`

**Comment by tomashapl** [comment]
Sorry, for confuse, we haven't release `<ButtonLink />` 🙈 but in this it will be
