### ISSUE TITLE
PictureCard: allow local images

### ISSUE THREAD

**Issue by jamessspanggg** [kiwicom/orbit-components#1834]
**Is your feature request related to a problem? Please describe.**
When using PictureCards, we can only use images from orbit-components. I want to use images from my project. (not sure if there's a way of achieving this)

**Describe the solution you'd like**
PictureCards should allow to pass entire src of image.

**Describe alternatives you've considered**
N.A

**Additional context**
N.A

**Comment by CollierCZ** [comment]
Would be fixed by #1544
