### ISSUE TITLE
Add align="baseline" into the Stack component

### ISSUE THREAD

**Issue by seeden** [kiwicom/orbit-components#1929]
Align baseline is not supported in the Stack component. But it is valid value and I would like to use it. Can you add this enum value? 
Thank you

Here is link with all valid values 
https://developer.mozilla.org/en-US/docs/Web/CSS/align-items
You used just values from the example.

**Comment by vepor** [comment]
Hello @seeden, thanks for the request.

We didn't have it on purpose and even though that we won't have probably use case for it, I'll add it 🙂

**Comment by seeden** [comment]
Thank you @vepor  :) I really appreciate it
