### ISSUE TITLE
useMediaQuery: JS is out of sync with CSS, `const { isTablet } = useMediaQuery()` is changing later than `media.tablet()`

### ISSUE THREAD

**Issue by sampi** [kiwicom/orbit-components#1966]
## Expected Behavior

`const { isBreakpointName} = useMediaQuery()` in JS would change at the same time as `media.breakpointName()` does in `styled-components`/CSS

## Current Behavior

`const { isBreakpointName} = useMediaQuery()` in JS changes visibly later (>50ms) than `media.breakpointName()` does in `styled-components`/CSS

## Possible Solution

Use a similar technique to this `useMediaQuery` hook: https://github.com/bence-toth/react-hook-media-query/blob/master/src/index.js 
That way there's no need to bother with `setTimeout` because changes will only trigger when there are actual changes to the results of the Media Queries and JS will be in complete sync with CSS.

## Steps to Reproduce

https://codesandbox.io/s/vibrant-ives-ukh8j?file=/src/index.js

1. Open Sandbox
1. Resize the viewport until it's above/below 768px
1. Watch as the background and font-size change (CSS breakpoint in `styled-components`)
1. Watch as the color and text changes (JS breakpoint from `useMediaQuery`)

## Context (Environment)

I need to move an element from one CSS Grid area from another one, based on the breakpoint and while resizing the page to be larger, I see a flash of the tablet layout with the mobile content and vice-versa.

I don't want to render the element twice and hide/show with CSS, it feels better to have React "teleport" the already rendered element into another position in the DOM and let the browser handle the heavy lifting.

**Comment by sampi** [comment]
Here are some screenshots of going from mobile to tablet view on the codesandbox playground:

![vlcsnap-2020-06-21-21h21m33s645](https://user-images.githubusercontent.com/524272/85233317-a8ea8780-b405-11ea-8657-f3abed2efce4.png)
![vlcsnap-2020-06-21-21h21m43s124](https://user-images.githubusercontent.com/524272/85233323-ab4ce180-b405-11ea-8669-99f30d9a160d.png)
![vlcsnap-2020-06-21-21h21m54s446](https://user-images.githubusercontent.com/524272/85233325-ac7e0e80-b405-11ea-9b6f-8bd545740541.png)

Here's a gif which was converted from a video from which the screenshots were taken:
![breakpoint-bug](https://user-images.githubusercontent.com/524272/85233382-01ba2000-b406-11ea-8c84-c57bd3de9ba3.gif)

**Comment by vepor** [comment]
Fixed in #1982
