### ISSUE TITLE
List Choice selected value

### ISSUE THREAD

**Issue by kouloughli-hemza** [kiwicom/orbit-components#2002]
Hello ,
i was working on ListChoice Component to show list of airports ,

`props.airportsFound.map((airport,key) => {
        return (<ListChoice
            key={airport.iata}
            description={airport.name}
            icon={<City />}
            value={airport.iata}
            onClick={(e) => console.log(e.target)}
            selectable
            title={airport.name + ' ' + airport.state}
        />)`

but i was unable to get the value of selected airport/airports .
i cannot find how to manupilate user data in documentation,
can you please guide me 
Thank you

**Comment by vepor** [comment]
Hello @kouloughli-hemza,

`ListChoice` component is not a HTML form element, so therefore it doesn't support `value` property and the easiest solution for your use case is to create inline callback inside the return of map, e.g. like this:
```js
airportsFound.map((airport, key) =>
  <ListChoice
    onClick={() => handleOnClick(aiport.iata)}
    // other props
  />
)
```  

Hopefully you'll find this useful.

**Comment by kouloughli-hemza** [comment]
Hello @vepor 
Thank you so much,
i feel stupid , i dnt know how i missed that idea ,
Thank you lot,
any update about new  **Itinerary** 
#1842

**Comment by vepor** [comment]
No problem 🙂 

We will focus on **Itinerary** in upcoming weeks. I think that development of it will start at the end of July.
