### ISSUE TITLE
CountryFlag missing HTML attributes, like alt

### ISSUE THREAD

**Issue by RobinCsl** [kiwicom/orbit-components#2041]
Hi 👋 

It seems that the following [code](https://github.com/kiwicom/orbit-components/blob/bbdcbb01a7f3f19756c0b382c17704c235f706b7/src/CountryFlag/index.js#L40-L51) only allows the attributes `class`, `src` and `srcset` to "survive" in the actual rendered DOM image node for the `CountryFlag` component. In particular, the `alt` attribute is missing, which is not great accessibility-wise.

Could it be that the `return` statement should also return the other props passed to `StyledImage`?

Thanks a lot :)

**Comment by vepor** [comment]
Hi @RobinCsl 👋 

Even though that the used of `attrs` on the component only returns `src` and `srcset`, passing of alt in the JSX is still allowed and it will be rendered in the DOM.

By default, it’s not there, as `name` is `null`. But if you pass any, it will be rendered. You can see this on [Playground story of CountryFlag](https://kiwicom.github.io/orbit-components/?path=/story/countryflag--playground).
