### ISSUE TITLE
Popover default close Button with Translation

### ISSUE THREAD

**Issue by kouloughli-hemza** [kiwicom/orbit-components#2051]
Hello,
recently im working on translation ,and found that `Popover` default close Button is not considering the dictionary used and not translating it always shows 'Close'.
 is this related to `Translate` component issue #2007  ?
 is there away to translate without using our own actions ? 

here is sandbox showing the issue : 
[https://codesandbox.io/s/happy-poitras-nmmw1](https://codesandbox.io/s/happy-poitras-nmmw1)

**Comment by silvenon** [comment]
Yep, it's the same reason 😃 read https://github.com/kiwicom/orbit-components/issues/2007#issuecomment-664654379 for explanation.
