### ISSUE TITLE
Button with icon on right

### ISSUE THREAD

**Issue by darkwindcz** [kiwicom/orbit-components#236]
We need to add the new feature to Button and ButtonLink - possibility to have an icon on the right side. 

## Visual style
![buttons with icon on right](https://user-images.githubusercontent.com/6851247/41983969-bedda200-7a2f-11e8-83c0-bb121c9b6edb.png)

Zeplin: https://zpl.io/bAqWKv8

### Interactions
Interactions are same as in classical buttons

## Storybook chapters
No new chapter, but please add new example to the chapter `Button with icon`

**Comment by wEprous** [comment]
Should be this functionality also added to ButtonLink? @darkwindcz

**Comment by darkwindcz** [comment]
`We need to add the new feature to Button and ButtonLink`

Well... what do you think? :D

**Comment by wEprous** [comment]
🤦‍♂️ Sorry, I missed that 😄
