### ISSUE TITLE
Create <Badge /> component

### ISSUE THREAD

**Issue by darkwindcz** [kiwicom/orbit-components#237]
## Description
Badges are non-clickable labels that communicate the status of any particular instance (e.g. booking).

## Visual style
![badges](https://user-images.githubusercontent.com/6851247/41987569-d7267b5c-7a39-11e8-9344-110b4e8a2a26.png)

Zeplin: https://zpl.io/2j4YyOA

### Interactions
As badge is non-clickable, there are not many interactions. Only interaction here is triggering something after hovering the badge, for example showing a tooltip.

### Additional information
- We have only one size
- It should have the possibility to show icon on the left side. 
- It should be possible to force circular shape - for notification badges (if it's not different component)

### Default
- Type: Neutral, with icon

### Badge types (not sure if one chapter or more)
- List of all types of badges
- Possibility to change: icon, text

### Notification badge
- Circle badge with a number inside
- Possibility to change the type
- No possibility to change/choose icon

**Comment by tomashapl** [comment]
#243
