### ISSUE TITLE
General Input

### ISSUE THREAD

**Issue by jakubzaba** [kiwicom/orbit-components#24]
Create general Input that will be used by all other specific inputs: `InputText`, `InputNumber`, ... and use it in all those inputs.

**Comment by VaclavSir** [comment]
I think the general input is the HTML `input` element. What else could inputs have in common?

**Comment by jakubzaba** [comment]
Basic design will be common but some rules will be in specific input, e.g. phone input, ...
We should optimize when it's needed, so wait for a while with this.

**Comment by oreqizer** [comment]
yep, the basic `Input` should just render `input`, but styled

**Comment by darkwindcz** [comment]
We have new issue for this #153, we should probably close this one
