### ISSUE TITLE
Allow Promise in onChange, onClick

### ISSUE THREAD

**Issue by Fallion** [kiwicom/orbit-components#247]
Currently we only allow functions, but nothing that can return a promise.

**Comment by wEprous** [comment]
Promise type was not added for eg. Radio in onChange method.

**Comment by wEprous** [comment]
Should be promise also in Card and Alert?

https://github.com/kiwicom/orbit-components/blob/46575d20a46c9bdf538337cdc1f8b17eac27365e/src/Card/index.js.flow#L6
https://github.com/kiwicom/orbit-components/blob/46575d20a46c9bdf538337cdc1f8b17eac27365e/src/Alert/index.js.flow#L12

cc @tomashapl

**Comment by wEprous** [comment]
Closing for now as there was no request for Promise types in `onClose` etc. prop.
