### ISSUE TITLE
Change of focus state in inputs

### ISSUE THREAD

**Issue by darkwindcz** [kiwicom/orbit-components#252]
We changed the focus state in form component to 2px blue border, check the specs in Zeplin.

https://zpl.io/aRYpZnz

Also for those components:
 - Input
 - Textarea
 - Select
 - Checkbox / Radio
 - File input

## Preview
![focus states](https://user-images.githubusercontent.com/6851247/42412504-ebb863e2-820d-11e8-96c9-7a8d84be0c74.png)

**Comment by wEprous** [comment]
Should we update all form components in one iteration? Textarea and InputField are not still implemented. cc @darkwindcz

**Comment by tomashapl** [comment]
Is it still required ? I think #303 solved this cc @wEprous @williamkolmacka

**Comment by wEprous** [comment]
Yes, solved in #303
