### ISSUE TITLE
Create <Separator /> component

### ISSUE THREAD

**Issue by darkwindcz** [kiwicom/orbit-components#262]
## Description
The separator is great for better scanability of two non-related content on the page or section.

## Visual style
![line specs](https://user-images.githubusercontent.com/6851247/42726848-c202fbf0-879b-11e8-83e8-5a3098ef605a.png)

Zeplin: https://zpl.io/agvw3P1

## Functional specs
- any better name welcomed
- it should generate <hr> tag, according to this (https://www.w3schools.com/tags/tag_hr.asp) 

## Storybook chapters
- probably just default

**Comment by tomashapl** [comment]
!295
