### ISSUE TITLE
Unable to have 2 or more buttons in one row

### ISSUE THREAD

**Issue by alizhdanov** [kiwicom/orbit-components#266]
The problem which I'm heading: I can't have >=2 buttons in one row. 

https://github.com/kiwicom/orbit-components/blob/833af5f51b0f2cad6d0d29ff5611f0c345bcdeb4/src/Button/Button.js#L50

Why is button `flex` and not `inline-flex`?
By default button element is inline (or inline-block).

**Comment by wEprous** [comment]
We will change that, it's obsolete styling. Sorry about that.

In the future, there will be ButtonGroup component, see #225

**Comment by alizhdanov** [comment]
@wEprous thank you for info.
I'm not sure if you're working on it too, but I'm experiencing the same problem with `Radio` component too.

**Comment by wEprous** [comment]
ButtonGroup added in #225 and released in v0.5.0
Currently, we are working on some Stack component which handles flex properties and some spacing for children. It will take some time to polished but, so can you wait until it will be released or do you want some hot-fix?
cc @alizhdanov

**Comment by alizhdanov** [comment]
It's fine. I can wait until Stack component.
Thanks.
