### ISSUE TITLE
New & update icons from Orbit UI for Sketch 0.23.0 release 

### ISSUE THREAD

**Issue by darkwindcz** [kiwicom/orbit-components#276]
New and updated icons: [icons.zip](https://github.com/kiwicom/orbit-components/files/2225222/icons.zip)

We also need to rename a few icons but be careful, it's breaking change (icons are part of the package)

```
baggage-big => baggage-checked
baggage-small => baggage-cabin
baggages => baggage-set
```

**Comment by wEprous** [comment]
Added & updated in #277
