### ISSUE TITLE
Support for Typescript

### ISSUE THREAD

**Issue by fallion** [kiwicom/orbit-components#324]
It is impossible to use this library with Typescript. It would be nice if it generated types for typescript as well, or better yet was rewritten for Typescript :D

**Comment by michalsanger** [comment]
How would the usage in Flow project be if it was written in Typescript?

**Comment by JuliusKoronci** [comment]
too bad as most of the react projects are using typescript..

**Comment by vepor** [comment]
We will eventually support TypeScript, it's not just priority for now - our consumers still heavily use Flow.

**Comment by fallion** [comment]
There are actually internal typings which could be published to DefinitelyTyped @vepor . Please ask the Balkan team.

**Comment by straxico** [comment]
I convert the project to typescript and use this in our company project
you can see temp version here:  https://github.com/straxico/react-strix/tree/master/src/Components/Atoms

**Comment by vepor** [comment]
@fallion I already know about that 🙂 but there won't be time at least until the end of 2019. Hopefully we manage to support Typescript fully in first quarter

**Comment by maxtuzz** [comment]
It's bonkers to me that this project is so well developed but still doesn't have typings available. Would be a huge help to publish those internal typings.

**Comment by iKethavel** [comment]
++ for typescript support

**Comment by dinodsaurus** [comment]
@vepor any update on this 🙏

**Comment by vepor** [comment]
Typescript definitions released in `0.85.0`
https://github.com/kiwicom/orbit-components/releases/tag/0.85.0
