### ISSUE TITLE
Text color in Select is on Windows in color of "placeholder"

### ISSUE THREAD

**Issue by designkiwicom** [kiwicom/orbit-components#334]
Check screenshot - it probably inherits color from "placeholder" style.

![selectbox-bug](https://user-images.githubusercontent.com/42716743/44948251-aecf3d00-ae1a-11e8-85e3-7aef2a2276d2.png)

## Possible Solution
Use Text Primary color for option tag.

**Comment by wEprous** [comment]
Fixed in #750
