### ISSUE TITLE
Add padding to InputField suffix

### ISSUE THREAD

**Issue by vbambuch** [kiwicom/orbit-components#335]
## Expected Behavior

Icons inserted into `suffix` property of `InputField` component should have the same padding as `prefix`.

## Current Behavior

It has no padding.

## Possible Solution

Add padding.

## Steps to Reproduce

1. Add icon into suffix property.
2. Render it. 
3. See
4. ...

## Context (Environment)

It hurts my eyes.

**Comment by wEprous** [comment]
@vbambuch fixed with use of `ButtonLink`?
