### ISSUE TITLE
Add some more attributes to <Modal> for testing and accessibility

### ISSUE THREAD

**Issue by PetrSnobelt** [kiwicom/orbit-components#383]
**Is your feature request related to a problem? Please describe.**
I'd like to write some tests which use a Modal component. At first, I'd like to close it, but because there are not attributes which can be used for easy selecting modal or its close button is hard to do so. 

**Describe the solution you'd like**
Allow some attribute (id or data-test) which allow me to select modal
Also, I recommend adding some attributes to modal's close button for example (taken from bootstrap Alert): 
```
<button type="button" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
```

**Comment by wEprous** [comment]
Closing, `dataTest` prop added in release `0.12.0`. There will be another issue for accessibility issues.
