### ISSUE TITLE
<Radio />: Circle's width getting squished when parent not having enough space

### ISSUE THREAD

**Issue by Radek-Palisa** [kiwicom/orbit-components#394]
## Expected Behavior
Circle to always maintain its width and height of 20px.

## Current Behavior

Circle is getting squished, meaning it's not maintaining it's width of 20px when it's sharing space with another component (e.g. info).

![image](https://user-images.githubusercontent.com/16268406/46136153-33a94d00-c247-11e8-829d-447ce7b206c6.png)

## Possible Solution
adding `flex: 0 0 20px`

## Steps to Reproduce
put a long text info to the alert and and narrow the width of the parent

**Comment by wEprous** [comment]
Fixed in #307
