### ISSUE TITLE
Select: help/error is positioned to whichever parent element has position relative

### ISSUE THREAD

**Issue by Radek-Palisa** [kiwicom/orbit-components#436]
## Expected Behavior
Help/error to be underneath the input field.

## Current Behavior
help/error is now placed to the first parent element that has position relative on itself.

![image](https://user-images.githubusercontent.com/16268406/46586370-e36b8f80-ca7d-11e8-80fc-a2ed676ee9ad.png)

## Possible Solution

1) Remove position absolute

or

2) put position relative on label, but then also include margin-bottom on the label so that the element underneath is not overlapping with the help/error

## Context (Environment)
using Orbit 0.13.0

**Comment by wEprous** [comment]
@Radek-Palisa did you mean Select component?
