### ISSUE TITLE
<InputField /> doesn't work on mobile Safari

### ISSUE THREAD

**Issue by kubp** [kiwicom/orbit-components#446]
## Expected Behavior

Deleting and typing should work on mobile Safari.

## Current Behavior

https://monosnap.com/file/lUESrYUdR6fZburDtZ1aPAlOqRXQyJ

## Context (Environment)

Orbit 0.9.0

**Comment by wEprous** [comment]
I tried to reproduce this bug, but everything works fine. Check [StackBlitz project](https://stackblitz.com/edit/react-sxfbzr).

**Comment by wEprous** [comment]
Any update @kubp? Is it working or still not?
