### ISSUE TITLE
Stack_Desktop properties - All elements are clumped up in IE

### ISSUE THREAD

**Issue by smallram** [kiwicom/orbit-components#465]
## Expected Behavior

Elements in order, everything is visible
![image](https://user-images.githubusercontent.com/8585215/46683253-0ae26980-cbf0-11e8-9cc4-e11bdec4f193.png)

## Current Behavior

All elements clumped up, FakeInput is to the right like in #457 
![](https://d2mxuefqeaa7sj.cloudfront.net/s_ADF19995DB7DB7AC40745C602BBCB55AE2A9900DBD550D200ED96C7C7777CEAC_1539004947127_image.png)

## Storybook Link
https://kiwicom.github.io/orbit-components/?knob-Grow=true&knob-Basis=auto&selectedKind=Stack&selectedStory=Desktop%20properties&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

**Comment by dominikbaranek** [comment]
Works well on IE now. Found there another issue in both IE and Chrome: https://github.com/kiwicom/orbit-components/issues/721

**Comment by wEprous** [comment]
Thanks, closing in behalf of #489
