### ISSUE TITLE
CarrierLogo_Two carriers - Carrier logos are aligned vertically in IE

### ISSUE THREAD

**Issue by smallram** [kiwicom/orbit-components#472]
## Expected Behavior

The logos should be diagonally positioned to each other.
![image](https://user-images.githubusercontent.com/8585215/46738769-4e47e100-cc9f-11e8-8008-17749b47e5ea.png)

## Current Behavior

The logos are positioned vertically.
![image](https://user-images.githubusercontent.com/8585215/46738799-5f90ed80-cc9f-11e8-9aff-67df4634de18.png)

## Storybook link
https://kiwicom.github.io/orbit-components/?selectedKind=CarrierLogo&selectedStory=Two%20carriers

**Comment by wEprous** [comment]
I couldn't reproduce this bug. Did you catch that in IE 11 or some other version? I was using IE 11.285

**Comment by smallram** [comment]
Seems to be OK now. 🤔

**Comment by wEprous** [comment]
OK. So closing this issue for now. Thanks.
