### ISSUE TITLE
<Button/> and <ButtonLink/>: Spacings

### ISSUE THREAD

**Issue by williamkolmacka** [kiwicom/orbit-components#509]
## Expected Behavior
Spacings are swapped when using Button with icons (on the left, on the right or on both sides)on Button sizes (normal, large). Same for ButtonLink.

## Current Behavior
Example on Large Button with an icon on left:
![current](https://user-images.githubusercontent.com/3984338/47154822-a99f5200-d2e3-11e8-9cde-041fc979aaf4.png)
Padding of the Button from left side is `12px` instead of `16px`. Same for `margin-right` of the icon where is `16px` instead of `12px`.

## Possible Solution
Just swap left paddings on the Button and right margins on the icon. Provide it for all Button sizes.
![new](https://user-images.githubusercontent.com/3984338/47155036-35b17980-d2e4-11e8-82a9-b4ca921d1e7d.png)

**Comment by wEprous** [comment]
What about other sizes? Is wrong only the large size or all of them?
Also, if possible, write the right spacings for all sizes separately 🙏 
@williamkolmacka

**Comment by williamkolmacka** [comment]
Already in written in Expected Behavior. The sizes are the same but they need to be swapped as I shown on the image preview for all sizes of Button and ButtonLink.
