### ISSUE TITLE
Modal: Custom width or max-content width 

### ISSUE THREAD

**Issue by bvego** [kiwicom/orbit-components#511]
The problem is that I'm trying to set the modal width to match my date picker.
What I'm trying to achieve: https://monosnap.com/file/Pc6mXg827PTHslVVMllUC77cr7cg4c
What default size is giving me: https://monosnap.com/file/zmAiWCiFvKFb6HSa4XwSMBizscdKRA
What size large is giving me: https://monosnap.com/file/qHLInBnXBZ8I7PflQ5UAhOC4nOjhXx

**Describe the solution you'd like**
Some prop to set the modal body to be width: max-content

**Describe alternatives you've considered**
None so far. size="large" doesn't cut it - the content fits, but looks ugly

**Comment by wEprous** [comment]
Closing for now. After discussion, we should stick to limited sizes.
