### ISSUE TITLE
[Orbit UI v0.29.0] New & renamed illustrations

### ISSUE THREAD

**Issue by darkwindcz** [kiwicom/orbit-components#517]
Almost all illustrations were changed (small tweaks with positioning mostly); a few were renamed and few were added. Hopefully, the full list of changes here:

New illustrations
- Nomad
- Success
- Error
- BusinessTravel
- MobileApp
- PlaceholderTours
- DesktopSearch

Renaming
- no-bookings => NoResults
- ~~timeline-transport-taxi => transport-taxi~~
- timeline-boarding => Boarding
- timeline-drop-baggage => BaggageDrop
- AirportTransport => TransportBus
- AirportTransportTaxi => TransportTaxi

[illustrations.zip](https://github.com/kiwicom/orbit-components/files/2502073/illustrations.zip)

All illustrations should be already optimized by tinypng.com :)

**Comment by wEprous** [comment]
Also rename AirportTransport => AirportTransportBus

**Comment by tomashapl** [comment]
> Also rename AirportTransport => AirportTransportBus

Should be only `TransportBus` right ?
