### ISSUE TITLE
<Loading loading=false> doesnt hide the element

### ISSUE THREAD

**Issue by zbycz** [kiwicom/orbit-components#522]
## Expected Behavior
`<Loading loading={false} />` should display nothing (according to docs on orbit.kiwi)

## Current Behavior
It shows all the time

## Steps to Reproduce
1. Go here https://kiwicom.github.io/orbit-components/?selectedKind=Loading&selectedStory=Playground
2. Uncheck the loading property checkbox
3. Still see spinner spinning

**Comment by zbycz** [comment]
Ehm, there is a note for different prop which explains this exception `Loading which doesn't have a children is always shown, even though that loading prop is set to false.`

Perhaps updating the docs could be fine? Its rather confusing if you dont use the children element.

**Comment by CollierCZ** [comment]
Fixed by #886
