### ISSUE TITLE
Support optgroup in Select component

### ISSUE THREAD

**Issue by bvego** [kiwicom/orbit-components#527]
Support `optgroup` in Select

maybe something like this:
```js
<Select
...
options={{
  "First opt group label": [{value: "first_option", label: "First option" }],
  "Second opt group label": [{value: "first_option", label: "First option in second group" }],
}}
```

**Comment by vepor** [comment]
Hey @bvego, do you consider this still as needed feature? We manage to create some API proposition a long time ago (a lot). I would like to close this issue - if not wanted anymore, or focus on that once ago 🙂

**Comment by bvego** [comment]
Hey there @vepor - sorry for the late reply. Yeah, you can close it if you want.

We currently don't need it in tequila, but if there becomes a need for it I can just reopen the issue if that's ok with you 😄

**Comment by vepor** [comment]
Okay, thanks for the response! 🙂
