### ISSUE TITLE
Unnecessary overflow: hidden in CardSection component

### ISSUE THREAD

**Issue by petrbr** [kiwicom/orbit-components#542]
Tooltip in low height CardSection component is cut off -https://monosnap.com/file/30yIwh27gYoWLRvgBShLs7GbO71bBq

## Expected Behavior
Tooltip should not be cut off.

## Current Behavior
Tooltip is cut off :)

## Possible Solution
I have two suggestions:
- Set `overflow: hidden` only for expandable Card (it's unnecessary in non-expandable sections)
- Expandable functionality without `overflow: hidden`

**Comment by tomashapl** [comment]
Should be fixed in #689
