### ISSUE TITLE
TileExpandable uncleared timeout

### ISSUE THREAD

**Issue by fajzen** [kiwicom/orbit-components#545]
https://github.com/kiwicom/orbit-components/blob/master/src/Tile/TileExpandable/index.js#L50

Please clear this timeout in `componentWillUnmount`, otherwise `setHeight()` throws error if `this.node.current` is empty - unmounted at that time.

**Comment by wEprous** [comment]
I think that clearing that timeout is not necessary.
I suggest that this will do the trick:
```jsx
  setHeight = () => {
    const { current } = this.node;
    if (current) {
      this.contentHeight = current.clientHeight;
    }
  };
```
