### ISSUE TITLE
Upgrade to Storybook v4

### ISSUE THREAD

**Issue by RobinCsl** [kiwicom/orbit-components#560]
React Native is meant to be a first class citizen in Storybook v4:
https://medium.com/storybookjs/whats-new-in-storybook-4-0-react-native-741c7f481bbb
https://medium.com/storybookjs/storybook-4-0-is-here-10b9857fc7de

So need to inquire and update to v4.

@darkwindcz Do you plan to migrate to v4 too?

Make sure these boxes are ticked before submitting a new issue:

* [x] I have checked that this is not a duplicate
* [x] I have added a label categorizing this under BLKN | Kiwicom | Icons | Global

**Comment by darkwindcz** [comment]
If it's worth the time updating, let's go for it :) But it's more the question for @wEprous and @tomashapl.

**Comment by wEprous** [comment]
Sure, we do :)

**Comment by wEprous** [comment]
Sure, we plan to migrate :)
