### ISSUE TITLE
Create <Tag /> component

### ISSUE THREAD

**Issue by darkwindcz** [kiwicom/orbit-components#586]
## Description
A tag is an interactive label that helps to separate pieces of similar information from each other.

## Visual style
![tags](https://user-images.githubusercontent.com/6851247/47934787-a6f24e80-ded8-11e8-94df-be7309ff61f0.png)

Zeplin: https://zpl.io/agrBnMO

### Interactions
- hover/active/focused states are in Zeplin
- is possible that there will be no focus state (as it won't be a `button` HTML tag, probably?)
- when a tag is closable/removable, there are hover/active states for an icon itself

### Additional information
- it should be possible to set state: default or selected
- when the state is selected, it should always have a close icon
- it should probably have properties for `onRemove` and `onClick` to being able to attach separate events
- it should be possible to use this component separately or inside of inputField

## Functional specs
- it should probably have properties for `onRemove` and `onClick` to being able to attach separate events

## Storybook chapters
- default, with an icon, selected, closable, playground
- _we can discuss more later, when it's ready_

**Comment by tomashapl** [comment]
@darkwindcz

**Comment by wEprous** [comment]
Tag component added in #674
