### ISSUE TITLE
Possibility to use Tag inside InputField

### ISSUE THREAD

**Issue by honzatmn** [kiwicom/orbit-components#587]
It is needed for the search form.

![tags in inputs](https://user-images.githubusercontent.com/6851247/47935515-dd30cd80-deda-11e8-8d55-7dc673d5765a.png)

Zeplin: https://zpl.io/aRE0YYE

Not sure what to specify more, behavior of tags is specified here: #586

**Comment by tomashapl** [comment]
@darkwindcz

**Comment by vepor** [comment]
Closing this, added in #892
