### ISSUE TITLE
Create <Popover /> component

### ISSUE THREAD

**Issue by honzatmn** [kiwicom/orbit-components#588]
## Description
A popover can be used as a container for additional content that can be displayed on top of the page.

## Visual style
![popover](https://user-images.githubusercontent.com/6851247/47937280-7dd5bc00-dee0-11e8-822d-ff4db9c811da.png)

Zeplin: https://zpl.io/agrBvoM

### Additional information
- Popover can be used with different types of trigger, for example, `Button`, `ButtonLink`, `Tag` or `TextLink`. We shouldn't limit it to any specific component, a trigger can be basically anything clickable.
- There is similar behavior for our search forms (layer on top of the page, containing original input). Not sure if Popover should solve it, I see that more as a new component - something like InputPopover, or similar.
- You can find the proposed mobile behavior in Zeplin. It's copied from how Popovers behave in our mobile app (the Close button position). We need to discuss it and make it probably more consistent with Tooltip and Modal behavior (3 different patterns currently).

**Comment by filipdanisko** [comment]
Released in 0.39.0 #1006
