### ISSUE TITLE
<Breadcrumbs /> component

### ISSUE THREAD

**Issue by darkwindcz** [kiwicom/orbit-components#589]
## Description
Breadcrumbs component is navigational component placed on top of the page for showing hieararchy of current page.

## Visual style
![breadcrumbs](https://user-images.githubusercontent.com/6851247/47953101-cfca2080-df78-11e8-88be-7ef0cfc4a55d.png)

Zeplin: https://zpl.io/anYQLWO

### Interactions
- Link will underline itself when hovered

### Additional information
- Last item is also URL

## Accessibility
- https://www.w3.org/TR/wai-aria-practices/examples/breadcrumb/index.html
- https://gist.github.com/jonathantneal/4037764

## Functional specs
- Not sure how it works with React, but it would be great to have correct semantics for this component, so it shows nicely in Google. More info can be found  or [here](https://coderwall.com/p/p0nvjw/creating-a-semantic-breadcrumb-using-html5-microdata) or [here](https://www.npmjs.com/package/react-semantic-breadcrumbs).

**Google preview**
<img width="633" alt="breadcrumbs-semantic" src="https://user-images.githubusercontent.com/6851247/47953082-8a0d5800-df78-11e8-8c7f-bd1534984ec8.png">

**Comment by tomashapl** [comment]
@darkwindcz
