### ISSUE TITLE
BE custom msg instead of generic errors

### ISSUE THREAD

**Issue by patrikrozar** [kiwicom/orbit-components#606]
Use this **ONLY** for reporting bugs. For requesting new features check [this link](https://orbit.kiwi/request-an-enhancement/).

## Expected Behavior
You should show what happens if you have it in response.

## Current Behavior
Registration form on the sign in modal. When you are trying to register the same email address BE is responding with custom msg and we are showing general error `try to reload the page.`

## Possible Solution
Use custom msg from the response.

## Steps to Reproduce
1. Click Manage my booking modal in the navbar sign in modal will pop up.
2. Choose option register. 
3. Fill the form with existing email address.
4. Submit.

## Screenshot
http://take.ms/5Ct6A

**Comment by wEprous** [comment]
Invalid, should be reported in `nitrolib`.
