### ISSUE TITLE
<CardSection expandable /> height not recalculated on window resize while the card is being open

### ISSUE THREAD

**Issue by Radek-Palisa** [kiwicom/orbit-components#608]
## Expected Behavior
When changing the width of the window, the height of the expandable card should adapt to fit its content

## Current Behavior
The height of the card stays static on resize and so if the card's child height changes, the content gets hidden

## Steps to Reproduce
Expand the card and then resize the window. 

## Context (Environment)
using orbit 0.17.1

**Comment by tomashapl** [comment]
Solved in #689
