### ISSUE TITLE
TextLink size prop

### ISSUE THREAD

**Issue by bvego** [kiwicom/orbit-components#614]
Please make the TextLink have the `size` prop as the Text component does. We need it currently on Tequila

**Is your feature request related to a problem? Please describe.**
Trying to make the TextLink have a smaller font-size as the Text component has

**Describe alternatives you've considered**
Hacking it in with css

**Comment by wEprous** [comment]
It’s by design without `size` prop. `TextLink` should always inherit `font-size` from its parent. This was discussed already it many times.

So, wrap it into `Text` component and set props, as you need. Also the `TextLink` will have `text-decoration: underline` in few weeks.
