### ISSUE TITLE
TextLink underline prop

### ISSUE THREAD

**Issue by bvego** [kiwicom/orbit-components#616]
Please add the underline prop for the TextLink component

Use case: https://monosnap.com/file/3OFFrI1hHJkBTqPF5c5HeBsWMQgGPj

**Comment by wEprous** [comment]
@darkwindcz can you please look into this? I think that we wanted unified anchors on all projects, where the decision if the anchor has underline or not is based in the tokens.

**Comment by wEprous** [comment]
The `TextLink` will have `text-decoration: underline` in few weeks by default. All links used from `orbit-components` will have some behaviour and there will not be `underline` prop in the near future.

**Comment by darkwindcz** [comment]
As @wEprous said, but I hope it will be sooner in a few weeks. :D 

From a design point of view, this pattern feels little weird - it looks like that one of the links is selected or something. If you have a list of links somewhere, they should be always in the same `type`, not mixing it like this.
