### ISSUE TITLE
<Modal /> doesn't close on click outside, throws an error instead

### ISSUE THREAD

**Issue by Radek-Palisa** [kiwicom/orbit-components#626]
## Current Behavior
Modal doesn't close on the click outside, instead it throws this console error

![image](https://user-images.githubusercontent.com/16268406/48266494-d3095480-e42f-11e8-9773-7cd560af7a75.png)

## Context (Environment)
orbit 0.19.0

**Comment by wEprous** [comment]
@Radek-Palisa is this problem fixed with updating `styled-components` to v4?

**Comment by Radek-Palisa** [comment]
Yes, it's fixed. 

Thanks, closing the issue now.
