### ISSUE TITLE
<InputStepper> min/max broken for 0

### ISSUE THREAD

**Issue by zbycz** [kiwicom/orbit-components#639]
## Expected Behavior
<InputStepper minValue={0} /> should stop incrementing at 0

## Current Behavior
min/maxValue is ignored for number 0

## Possible Solution
The condition is broken:
`value: maxValue && newValue > maxValue ? maxValue : newValue,`

We should use something like `typeof value === "number"`.
Also i'd suggest setting `value` instead `maxValue` when over boundary. Otherwise you could never reach zero again in eg. step=2 default=0 and maxValue=3.

## Steps to Reproduce
1. open components [playground](https://kiwicom.github.io/orbit-components/?selectedKind=InputStepper&selectedStory=Playground&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)
2. click decrease button 
3. observe values lower than 0

**Comment by tomashapl** [comment]
@darkwindcz
