### ISSUE TITLE
TileExpandable does not adjust set height when children props is changed

### ISSUE THREAD

**Issue by prztrz** [kiwicom/orbit-components#642]
Once `children` prop is updated, `Tile` component does not adjust it's height to the new children prop. Propably the reason is that `setHeight` is set in `componentDidMount` but not in `componentDidUpdate` phase.

## Possible Solution
Add `this.setHeight` to component did update method

## Steps to Reproduce
1. wrap `Tile` in:
```js
const Wrapper = styled.div`
    &.inactive {
       display: none
    }
`;
```

2. Create stateful parent for Everything
```js
class Parent extends React.component {
    state = { isActive: false }


    componentDidMount() {
        setTimeout(() => this.setState({isActive: true}, 100);
    }

    render() {
        return (
            <Wrapper className={this.state.isActive ? 'active' : 'inactive'} >
                <Tile><br/><br/><br/><br/><br/>text<br/><br/><br/><br/></Tile>
            </Wrapper> 
        )
    }
}
```

3. Render `Parent`

**Comment by Radek-Palisa** [comment]
I think this is related to this https://github.com/kiwicom/orbit-components/issues/608. Recalculating the height will have to be triggered also on the window resize event to reflect the scenario when the child hasn't changed but its content height has (e.g paragraph text height growing on mobile screens).
