### ISSUE TITLE
<Modal> on ESC key all opened modals are closed

### ISSUE THREAD

**Issue by xtursky** [kiwicom/orbit-components#643]
## Expected Behavior
To not close all opened modals after ESC key is pressed.

## Current Behavior
I've two (or more) modals opened at once. 
Eg. modal with Form and some Confirmation on top of that.
After ESC key is pressed both modals are closed. Probably because event is propagated to all modals.

## Possible Solution
Stop event propagation on handle ESC key.

## Context (Environment)
See attachment

![2018-11-20_162723](https://user-images.githubusercontent.com/1123830/48784854-cca69280-ece3-11e8-8606-d1f091dcad9c.png)

**Comment by MichalMaM** [comment]
@xtursky is my idea right?

**Comment by wEprous** [comment]
@MichalCab Yes, it is. The `event` bubbles.
