### ISSUE TITLE
Support tabIndex prop in Button

### ISSUE THREAD

**Issue by martin-zsiros** [kiwicom/orbit-components#646]
**Is your feature request related to a problem? Please describe.**

Keyboard navigation (on landing page of Search) breaks when user tries to tab through all inputs to search button. That one is skipped and focus goes back to the top of the page, because Orbit button cannot have tabindex assigned.

**Describe the solution you'd like**

Please add tabIndex as optional prop to buttons, so focus order of elements can be overridden when necessary.

**Describe alternatives you've considered**

I have considered wrapping Orbit button into another normal button and move logic there as an ugly hack. Button is focusable in correct order with tab and triggerable with space/enter, but React complains that button tag shouldn't be nested within another button.

Solution nr. 2 was to use different element type (just plain div) as wrapper, but that would force me to attach custom listeners to watch for enter/space keypresses, which would be even more work for bad solution.

**Comment by tomashapl** [comment]
@darkwindcz
