### ISSUE TITLE
Move Label component out of Input folder and let it accept for Typography "types"

### ISSUE THREAD

**Issue by git-toni** [kiwicom/orbit-components#66]
It seems [Label](https://github.com/kiwicom/react-kiwi-ui/blob/master/blkn/src/Input/Label.js) can be used not only for `Input`-based types but also for other cases such as `Select`. I suggest to:

-  [ ] Move `Label` to its own folder.
-  [ ] Let `Label` accept different `type` props, so the `Typography` color it is using is more flexible. Currently it can only be either `secondary` or `primary`, which is not enough for `Select` for example.

Make sure these boxes are ticked before submitting a new issue:

* [x] I have checked that this is not a duplicate
* [x] I have added a label categorizing this under BLKN | Kiwicom | Icons | Global

**Comment by tomashapl** [comment]
@darkwindcz Can I close it ? `<FormLabel />` is available since #219

**Comment by wEprous** [comment]
@tomashapl I think you can.

**Comment by darkwindcz** [comment]
@tomashapl Yes
