### ISSUE TITLE
Extending Heading component by title5 & div possibility

### ISSUE THREAD

**Issue by darkwindcz** [kiwicom/orbit-components#661]
I thought that we could work without this style, but with the ongoing support of Search, we need a new style. We also need `div` as an element, it should have been there already, but we missed it probably. So we can add it with this :) 

**Describe the solutions you'd like**
1) Title 5: uppercase, text attention color, 12px, bold font weight
2) Allow having `div` as `element` prop

**Describe alternatives you've considered**
No alternatives. 

**Additional context**
We can probably remove `uppercase` prop from `<Text>`, but be careful with that, it can be breaking change.

**Comment by wEprous** [comment]
I would not remove the `uppercase` prop from `Text` component yet. I would rather delete it from `docs` and suggest using `title5`. What do you think @darkwindcz?
