### ISSUE TITLE
ListItem cannot be undefined or null

### ISSUE THREAD

**Issue by flanzana** [kiwicom/orbit-components#670]
Example from our code:
```
<List>
{document && <ListItem>{document}</ListItem>}
<ListItem>{insurance}</ListItem>
</List>
```

If there is no document, we don't want to display ListItem, so we used a condition, but flow finds an error: 
Flow: Cannot create `List` element because inexact null or undefined [1] is incompatible with exact `React.Element` [2] in array element of property `children`.

**Comment by wEprous** [comment]
Also another report:
<img width="885" src="https://user-images.githubusercontent.com/7254437/54208708-b4e65a80-44dc-11e9-8e8f-4e4d52e23ed2.png">

**Comment by Taym95** [comment]
Hello, how would you fix this? allow rendering null or undefined? I'm new to your library but I would like to work on this issue!

**Comment by wEprous** [comment]
Thanks for the interest @Taym95 but there is already prepared #881 for fixing this issue. Feel free to look at any other unassigned issue!
