### ISSUE TITLE
<Tile /> security issue: External linking gives 3rd party sites control over our site

### ISSUE THREAD

**Issue by underyx** [kiwicom/orbit-components#675]
See https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/ for example. Basically setting just `target="_blank"` adds our Kiwi.com page into the JavaScript context of the opened page, letting the opened 3rd party page manipulate our Kiwi.com page.

## Possible Solution

When external is true, set also `rel="noopener noreferrer"` on the link.

**Comment by underyx** [comment]
Thanks for the quick fix! I just noticed that Button and TextLink seems to have the same feature though and the security issue is still there :( @wEprous could you check if there are any other similar problems?

**Comment by wEprous** [comment]
OK, I'll check it and prepare PR if needed :)
