### ISSUE TITLE
<CardSection> inside <CardSection expandable> not fully displayed

### ISSUE THREAD

**Issue by flanzana** [kiwicom/orbit-components#676]
## Current Behavior

I tried to add CardSection inside expandable CardSection but when you first expand cardsection, the inner cardsection is not displayed fully: https://monosnap.com/file/5Q3Mnx3xsG5LLFTjJo41xTDb1P3lNT
You have to close and open cardsection few times to finally see the whole content. 

## Steps to Reproduce
- I made an example: https://codesandbox.io/s/j3wz264333
- Orbit 19

## Expected Behavior

The whole content of inner CardSection should be displayed on the first click on expanding card.
Like this: https://monosnap.com/file/SeQEDJuZE8G0bgw31z0BMOnRUjDCnA

**Comment by tomashapl** [comment]
I am not sure if this is right design pattern, CardSection should be always wrapped with Card
