### ISSUE TITLE
Add Storyshots

### ISSUE THREAD

**Issue by Fallion** [kiwicom/orbit-components#68]
Make sure these boxes are ticked before submitting a new issue:

* [x] I have checked that this is not a duplicate
* [x] I have added a label categorizing this under BLKN | Kiwicom | Icons | Global

We should automatically create snapshots from Storybook to prevent Storybook breaking. 

https://github.com/storybooks/storybook/tree/master/addons/storyshots

**Comment by michalsanger** [comment]
Please only if it does not produce one huge snapshot file. No one reads that during code review

**Comment by Fallion** [comment]
@michalsanger Huge snapshot file is fine if it shows only relevant changes. The issue with the implementation on Balkan was that classnames were generated for the entire project instead of each component. So when you updated classnames you would update all of the classnames, rendering it unreadable.

**Comment by michalsanger** [comment]
It's not fine to have files in PR no one reads and updates blindly when it's broken. It just bring illusion of being tested

**Comment by Fallion** [comment]
So you’re saying that snapshot tests have no purpose?

**Comment by Fallion** [comment]
Our aim should be to have functioning documentation via Storybook. How do you want to guarantee that all components still render?

**Comment by michalsanger** [comment]
I'm saying having huge snapshot file is a problem, because if developer accidentally updates it no one will review those changes, because the file will be big and messy. It's the same with PR with 10 changed files vs 100 changed files. Or how many times do you review content of `yarn.lock`?

Having snapshots per component looks better to me.

**Comment by Fallion** [comment]
But Github shows you only the changes between master and the branch. What does it matter if it's big if it shows only the relevant changes? 

I can check if Storyshots allows per story files yet.

**Comment by michalsanger** [comment]
Are the changes readable? Will you understand that the snapshot change is OK or it's broken? This should come with easy visual verification. Generate storybook for every PR or maybe even faster generate gallery of screenshots

https://www.npmjs.com/package/storybook-chrome-screenshot

**Comment by Fallion** [comment]
Does GitHub allow you to view visual changes between images?

The changes are DOM output changes. They should be readable.

**Comment by michalsanger** [comment]
I don't need visual testing 🚀 science. I need quick way to see component works. I can spent few seconds running through images when I see something was changed in storyshots. But it would suck if I would have to checkout the branch, install deps, run storybook, find the story...

**Comment by Fallion** [comment]
Thanks. We will use the visual storyshot testing.

**Comment by Fallion** [comment]
Closed in favour of #75
