### ISSUE TITLE
Media queries in orbit-components vs nitro

### ISSUE THREAD

**Issue by tibor-kulcar** [kiwicom/orbit-components#680]
Media queries defined in orbit-components are not aligned with values defined in nitro components.

## Expected Behavior
There should be defined the same breakpoints in both libraries to be able to use them together.

## Current Behavior
Now <Mobile> component in nitro has breakpoint at 768px but orbit component <Stack> has breakpoint at 600px.

**Comment by wEprous** [comment]
Media queries will be added in #572 and they will be the only media queries based on the `styled-components` for orbit/nitro and other projects.

**Comment by wEprous** [comment]
Media queries added in #572
