### ISSUE TITLE
Styled Components vs Styled JSX findings

### ISSUE THREAD

**Issue by Fallion** [kiwicom/orbit-components#7]
Aggregation of findings on this topic.

**Comment by tomashapl** [comment]
I'm for using styled component because of:

NESTING

just one reason but big one.
Code will be clearer

**Comment by michalsanger** [comment]
What is BEM for when you use CSS-in-JS?

**Comment by michalsanger** [comment]
@jaroslav-kubicek and @VaclavSir should be OK with that since they are doing code reviews

**Comment by VaclavSir** [comment]
> previous plan to try both

Problem is that we don't really try even the current approach. All teams that were originally supposed to use Orbit Components already decided not to use them "at this moment". 😞

**Comment by infi-pc** [comment]
Yeah, I heard :( but it seems to be better to use custom components until the component lib is stable. I mainly mean to try when developing those components. For the user of these components, it shouldn't really matter how CSS is written inside.

**Comment by jaroslav-kubicek** [comment]
I personally don't see any benefit in bringing a new approach into the codebase. I thought we decided to go with Styled JSX and suddenly introducing Styled Components doesn't make any sense to me, just additional overhead by rewriting components from one approach to another, sooner or later.  ¯\_(ツ)_/¯

**Comment by infi-pc** [comment]
actually, we didn't decide on JSX :), it was just random pick when we didn't want to spend too much time on both techs

**Comment by infi-pc** [comment]
just to explain the reasoning about that, 3/4 guys in Brno said they don't like Styled JSX and they would like to rewrite it to Styled components. And if they are the main people who should create the components I think they have right to choose what they want to use. So I just want to give them a chance to show us that their favorite tech is the one and we can evaluate it before releasing a stable version. I don't want to create some technology war between us. @jaroslav-kubicek @VaclavSir

**Comment by wEprous** [comment]
Closing this issue, components are already developed in `styled-components`.
