### ISSUE TITLE
 Can't yarn because of har-validator

### ISSUE THREAD

**Issue by VaclavSir** [kiwicom/orbit-components#700]
When I clone this repo and run `yarn`, it fails:

<img width="1123" alt="screenshot 2018-12-12 at 14 23 36" src="https://user-images.githubusercontent.com/1473642/49872506-98714e00-fe19-11e8-87e5-f7707124c5eb.png">

The `yarn.lock` references a version that has been unpublished: https://github.com/ahmadnassri/node-har-validator/issues/112

## Expected Behavior

Installs dependencies

## Current Behavior

Fails to install dependencies

## Possible Solution

Either fix `yarn.lock` manually, or just delete it and generate a new one.

## Steps to Reproduce

1. `git clone git@github.com:kiwicom/orbit-components.git`
2. `cd orbit-components`
3. `yarn`

**Comment by wEprous** [comment]
Fixed in #701
