### ISSUE TITLE
Stack_Desktop properties - Button misaligned if width <600px

### ISSUE THREAD

**Issue by dominikbaranek** [kiwicom/orbit-components#721]
## Expected Behavior
If width > 600px, the sign in button is aligned with the input field:
![image](https://user-images.githubusercontent.com/29459189/50686743-dfb8bc00-101e-11e9-83df-9a9b3633cf4a.png)

Works well in Stack_Nested example

## Current Behavior
If width < 600px, the sign in button is above intended position:
![image](https://user-images.githubusercontent.com/29459189/50686778-00811180-101f-11e9-9a9d-889eaba55b23.png)

**Comment by wEprous** [comment]
The behavior is alright, it should not be considered as a bug.
It's preview only for the desktop properties, so the mobile - default props are not used and the `align-items` won't work on viewport width < 600px.
