### ISSUE TITLE
<TripSegment> doesn't open all the way in storybook

### ISSUE THREAD

**Issue by jozefspisiak** [kiwicom/orbit-components#758]
Open trip segment in storybook and click on it, it will not show all contents

## Expected Behavior

it should open and show all the contents

## Current Behavior

It shows only half of first line of content

## Steps to Reproduce

1. Go to storybook:  https://kiwicom.github.io/orbit-components/?selectedKind=TripSegment&selectedStory=Default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel
2. Click on Trip Segment
3. Click on Default
4. Click on the segment to open more information

## Context (Environment)

We would like to migrate search results to start using it if it is ready

**Comment by tomashapl** [comment]
@wEprous there is wrongly calculated may-height

![image](https://user-images.githubusercontent.com/7850592/51389101-93e03980-1b2b-11e9-8412-e256e677d5bc.png)

could you fix this ASAP pls 🙏
