### ISSUE TITLE
ServiceLogo_Alipay, PayPal and Trustly not cropped properly

### ISSUE THREAD

**Issue by smallram** [kiwicom/orbit-components#765]
## Expected Behavior
The logo should not have any white space before or after it, such as here:
![screenshot-kiwicom github io-2019 01 21-06-04-53](https://user-images.githubusercontent.com/29459189/51453930-7df89180-1d42-11e9-8d05-8f954b77168b.png)

## Current Behavior
There is white space to the right of the Alipay, PayPal and Trustly logos:
![screenshot-kiwicom github io-2019 01 21-06-00-01](https://user-images.githubusercontent.com/29459189/51453825-e85d0200-1d41-11e9-9d9d-f4262e27eea4.png)
This causes it to be misaligned for example in InputField:
![screenshot-kiwicom github io-2019 01 21-06-02-01](https://user-images.githubusercontent.com/29459189/51453860-1a6e6400-1d42-11e9-851f-60812fb104f4.png)

[Storybook](https://kiwicom.github.io/orbit-components/?selectedKind=ServiceLogo&selectedStory=Playground&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)

**Comment by tomashapl** [comment]
Reuploaded logos, thanks 👏
