### ISSUE TITLE
<Tooltip> has z-index problem when used in <Modal>

### ISSUE THREAD

**Issue by tibor-kulcar** [kiwicom/orbit-components#796]
Tooltip is under Modal's backdrop and therefore is not visible

## Expected Behavior
Tooltip should be visible in Modal also

## Steps to Reproduce
<img width="515" alt="screen shot 2019-02-08 at 17 45 40" src="https://user-images.githubusercontent.com/3975660/52493970-0abd9f00-2bcd-11e9-9b8e-51e08e51ff40.png">

## Context (Environment)
Used in search project

**Comment by wEprous** [comment]
Fix already prepared in #793.
Please consider looking into existing issues/PRs next time, so there is no not-needed issue 🙏

**Comment by tibor-kulcar** [comment]
Sorry about that, I'll check it next time thoroughly.
