### ISSUE TITLE
<Radio> - data-test is rendered on invisible element

### ISSUE THREAD

**Issue by petrbr** [kiwicom/orbit-components#807]
## Expected Behavior
`data-test` should be on visible (and clickable for tools like Cypress) element.

## Current Behavior
It's on invisible input element and Cypress can't click on it. 
![image](https://user-images.githubusercontent.com/33488156/52626042-a2afd700-2eb2-11e9-8cd1-04030a9c58c8.png)

## Possible Solution
Move data-test from input to label.

**Comment by vepor** [comment]
Closing because there was not proper solution in past time and it's possible to use `dataTest` in cypress e2e tests anyway.
