### ISSUE TITLE
<Modal>

### ISSUE THREAD

**Issue by petrbr** [kiwicom/orbit-components#837]
ModalFooter on small devices (320 px width) with two buttons and long text can be broken https://take.ms/NVfH0

**Comment by wEprous** [comment]
@petrbr can you just specify some usage context? From the screenshot, it doesn't look that those buttons are wrapped in ModalFooter

**Comment by wEprous** [comment]
I'm closing this as you @petrbr didn't get me better information or usage context for this case. If you gonna have time, please create another proper issue 🙏
