### ISSUE TITLE
Fix InputFile overflowing

### ISSUE THREAD

**Issue by tomashapl** [kiwicom/orbit-components#891]
## Expected Behavior
Text in InputFile shouldn't overflow component

## Current Behavior
![image](https://user-images.githubusercontent.com/7850592/53965221-0fed0b80-40f1-11e9-9358-f5b9578e1060.png)

**Comment by MatejTuray** [comment]
Hello, are you open for PR's?

I would like to work on this

![56749092_352464472039568_476312663400382464_n](https://user-images.githubusercontent.com/41123694/55741409-7b4a3600-5a2d-11e9-8d4a-12168cef3a50.png)

setting 

`overflow: hidden;`
`text-overflow:ellipsis;`

seems to fix the overflowing issue

live url : https://orbit-components-fix-inputfile-overflowing.surge.sh

**Comment by vepor** [comment]
Hi @MatejTuray 👋
Yes, we are open to any contribution that fixes issues labeled by `Help appreciated`! 🙂

**Comment by vepor** [comment]
Fixed in #993
