### ISSUE TITLE
Create <Button /> component

### ISSUE THREAD

**Issue by darkwindcz** [kiwicom/orbit-components#94]
## Description
The button is a simple component when we use for showing what actions users can do on the page.

## Visual style
![](https://d2mxuefqeaa7sj.cloudfront.net/s_32566EF5967BC4836E563D62DD1CF745317F409CCB15BA073AEE04B8DADB76C8_1521224821486_buttons-set.png)

## Parameters

Parameter | Values | Default
-- | -- | --
Style | Primary, Secondary, Link, Facebook, Google, Destructive | Primary
Size | Large, Normal, Small | Normal
Icon | [string] | empty
Label | [string] | Your label
Bordered | [boolean] | false
Disabled | [boolean] | false
Loading | [boolean] | false
Width | [string] | auto

### For all configurations
```
font-family: $fontFamily
border-radius: $borderRadiusNormal
font-weight: $fontWeightBold
min-width: $widthButtonMinimal
```

### Additional information
- Vertical centering for icon and text label
- For all buttons, there should be a transition for changing states (for background color and scale properties)
- Borders in bordered version are inside the button, so the height of the button stays same
- Width is usually calculated automatically (based on length of label + icon width + paddings). However, it should be possible to set up width manually so there is a chance to have two same-width buttons when placed near each other.
- All buttons should disable all the default browser styling so it doesn’t mess with our own visual style (http://www.456bereastreet.com/i/button_d.png) 
  
### Based on selected configuration:

Parameter:Value | property: $token
-- | --
Style:Primary | text color: `$colorTextButtonPrimary`<br>icon color: `$colorIconButtonPrimary`<br>background: `$backgroundButtonPrimary`<br><br>**For bordered version:**<br>text color: `$colorTextButtonPrimaryBordered`<br>icon color: `$colorIconButtonPrimaryBordered`<br>background: `$backgroundButtonBordered`<br>border-color: `$borderColorButtonPrimaryBordered`
Style:Secondary | text color: `$colorTextButtonSecondary`<br>icon color: `$colorIconButtonSecondary`<br>background: `$backgroundButtonSecondary`<br><br>**For bordered version:**<br>text color: `$colorTextButtonSecondaryBordered`<br>icon color: `$colorIconButtonSecondaryBordered`<br>background: `$backgroundButtonBordered`<br>border-color: `$borderColorButtonSecondaryBordered`
Style:Link | text color: `$colorTextButtonLink`<br>icon color: `$colorIconButtonLink`<br>background: `$backgroundButtonLink`<br><br>**For bordered version:**<br>N/A _(there is no bordered version for this so if someone enable this style together with “bordered”, we'll just ignore it?)_
Style:Facebook | text color: `$colorTextButtonFacebook`<br>icon color: `$colorIconButtonFacebook`<br>background: `$backgroundButtonFacebook`<br><br>**For bordered version:**<br>text color: `$colorTextButtonFacebookBordered`<br>icon color: `$colorIconButtonFacebookBordered`<br>background: `$backgroundButtonBordered`<br>border-color: `$borderColorButtonFacebookBordered`
Style:Google | text color: `$colorTextButtonGoogle`<br>icon color: `$colorIconButtonGoogle`<br>background: `$backgroundButtonGoogle`<br><br>**For bordered version:**<br>text color: `$colorTextButtonGoogleBordered`<br>icon color: `$colorIconButtonGoogleBordered`<br>background: `$backgroundButtonBordered`<br>border-color: `$borderColorButtonGoogleBordered`
Style:Destructive | text color: `$colorTextButtonDestructive`<br>icon color: `$colorIconButtonDestructive`<br>background: `$backgroundButtonDestructive`<br><br>**For bordered version:**<br>text color: `$colorTextButtonDestructiveBordered`<br>icon color: `$colorIconButtonDestructiveBordered`<br>background: `$backgroundButtonBordered`<br>border-color: `$borderColorButtonDestructiveBordered`
Size:Large | font-size: `$fontSizeTextLarge`<br>height: `$heightButtonLarge`<br>padding-left: `$paddingButtonLarge`<br>padding-right: `$paddingButtonLarge`<br><br>**When button has icon:**<br>padding-left: `$paddingButtonLargeWithIcon`<br><br>**Styles for inserted icon:**<br>height: `$heightIconMedium`<br>width: `$widthtIconMedium`<br>margin-right: `$marginButtonIconLarge`
Size:Normal | font-size: `$fontSizeTextNormal`<br>height: `$heightButtonNormal`<br>padding-left: `$paddingButtonNormal`<br>padding-right: `$paddingButtonNormal`<br><br>**When button has icon:**<br>padding-left: `$paddingButtonNormalWithIcon`<br><br>**Styles for inserted icon:**<br>height: `$heightIconMedium`<br>width: `$widthtIconMedium`<br>margin-right: `$marginButtonIconNormal`
Size:Small | font-size: `$fontSizeTextSmall`<br>height: `$heightButtonSmall`<br>padding-left: `$paddingButtonSmall`<br>padding-right: `$paddingButtonSmall`<br><br>**When button has icon:**<br>padding-left: `$paddingButtonSmallWithIcon`<br><br>**Styles for inserted icon:**<br>height: `$heightIconSmall`<br>width: `$widthtIconSmall`<br>margin-right: `$marginButtonIconSmall`
Loading:true | Nothing so special, it's basically just a button with specific icon. For this, we'll use animated icon from our old button: [Loading button in storybook](https://www.kiwi.com/storybook/?knob-Visa%20required%3A=false&knob-Cuba%20regulation%3A=false&knob-Kind=primary&knob-Size=medium&knob-Fullwidth=false&knob-Disabled=false&knob-Loading=false&knob-text=button%20text&selectedKind=Components%2FButton&selectedStory=loading-blue&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybooks%2Fstorybook-addon-knobs)

## Pre-defined configurations
There is few combination we can predefine. All this configuration matches names and look for Sketch symbols from our Orbit UI kit. It should also help with handing designs over to product teams.

This gives us also possibility that for eg. when we change the default icon for a destructive button will be “cross” instead of “remove”, that we don’t need to go through all instances and change it everywhere. We just change that pre-defined configuration for “Destructive button” have “icon” parameter set to “cross” and it’ll change everywhere.

Type | Pre-defined parameters | Usually working with
-- | -- | --
Primary button | Style: Primary<br>Size: Normal | Size<br>Label<br>Disabled<br>Loading
Primary button with icon | Style: Primary<br>Size: Normal<br>Icon: “plus-circle” | Size<br>Label<br>Disabled<br>Loading
Secondary button | Style: Secondary<br>Size: Normal | Size<br>Label<br>Icon<br>Disabled<br>Loading
Secondary button with icon | Style: Secondary<br>Size: Normal<br>Icon: “plus-circle” | Size<br>Label<br>Icon<br>Disabled<br>Loading
Destructive | Style: Destructive<br>Size: Normal<br>Icon: “remove” | Size<br>Label<br>Disabled<br>Loading
Destructive Light | Style: Destructive<br>Size: Small<br>Bordered: true<br>Icon: “remove” | Size<br>Label<br>Disabled<br>Loading
Facebook | Style: Facebook<br>Size: Normal<br>Icon: “facebook” | Size<br>Label<br>Disabled<br>Loading
Google | Style: Google<br>Size: Normal<br>Icon: “google” | Size<br>Label<br>Disabled<br>Loading
Button Link | Style: Link<br>Size: Small<br>Icon: “plus-circle” | Size<br>Label<br>Disabled<br>Loading

Of course that is possible to define custom configuration but it won’t be recommended and if we decide that we need to use eg. light variants of our buttons more, we can always add another pre-defined state.

## Hover & active button states
![](https://d2mxuefqeaa7sj.cloudfront.net/s_32566EF5967BC4836E563D62DD1CF745317F409CCB15BA073AEE04B8DADB76C8_1521289858732_button-states.png)

You can check interactions on this link, Version 5 is the one we choosed: https://codepen.io/darkwindcz/pen/mxJmbP

When are **buttons hovered**, we use `darken()` function for background colors for our button backgrounds in most cases, e.g. `darken([original-color], $modifierDarkenHover)`. Same darken modifier is used for text and border colors when button is in “Bordered” version. 

When are **buttons active**, we use `darken()` function for background colors for our button backgrounds in most cases, e.g. `darken([original-color], $modifierDarkenActive)`. Also, when button is active, we scale it's size down, with the css function `transform: scale($modifierScaleButtonActive)`

The design token name for darkening value is not tight to buttons as we use the same token for hover state of different components (like `<TextLink />` or in the future for `<Chip />`, etc.)

**There is one exception though.** For button style “Link”, we want to use `$backgroundButtonLinkHover `instead of darkening pure white. The reason for this is that if we would use `darken(#fff, 5%)`, it would generate gray-ish color. But in our color system, we use blue-ish versions of our gray shades. For active state of this button, we just use darken with this vaues: `darken($backgroundButtonLinkHover, $modifierDarkenButtonLink)`.

**Hover & active states are same for all** button sizes and button styles. (With exception of Link type, as mentioned above)

**Disabled state** should use opacity $opacityButtonDisabled, hover styles should be disabled too so it doesn’t look like there is some interaction behind it. 

**Focus state** should use default browser styling (outline). It’s possible that we'll change it in the future with our own defined box-shadow, but we need to discuss this with designers.

## Some inspiration from other’s React components for button component:
https://mineral-ui.com/components/button
http://design-system.pluralsight.com/components/button/
https://seek-oss.github.io/seek-style-guide/button
https://seek-oss.github.io/seek-style-guide/button (there is nice loading animation :-) 
https://polaris.shopify.com/components/actions/button#navigation (they have also some accessibility parameters)
http://design.acl.com/component/Button (I like their naming convention for states, eg. isDisabled or isLoading)

**Comment by Fallion** [comment]
Icon should be a string?

**Comment by darkwindcz** [comment]
@Fallion For me it's string because it's just the name of the icon, like "attachment", "plus-circle" or "remove". When I explored some React components, I've seen few styles and I just liked the "string" as the easiest one. 

But everyone is solving this with their own style, we should do what we think is best for us:

- [Shopify](https://polaris.shopify.com/components/actions/button#navigation) have just list of icons you can use. This can be good if you don't want someone to use a button that is not in your icon set.
- [Instacart](https://instacart.github.io/Snacks/#!/Button/11) allows string or element.
- [CA Technolgies](https://mineral-ui.com/components/button) have `React$Element`
- [Pluralsigh](http://design-system.pluralsight.com/components/button/) have Icon component
- [Seek](http://seek-oss.github.io/seek-style-guide/button/) adds icons inside the component same as where they put a label


But take these my params proposals more like reference what should we be able to set for every instance of a component.

**Comment by Fallion** [comment]
Just trying to start a conversation around this. We're using React$Element right now so it's up to @jaroslav-kubicek and the team whether to use strings or an <Icon />

**Comment by darkwindcz** [comment]
I personally just don't like this one:

```javascript
<Button icon={<Icon name="remove" />}>
    Remove booking
</Button>
```

The string inside is repetitive for each instance and renaming anything in the `<Icon />` component would be hell.

But these specifications are basically starter of a conversation as well. Nothing is set in stone and is very open to discussion.

**Comment by FilipMessa** [comment]
The element is better, I think. Because if you want to use a string you must have all possible icon already imported, even if you don't use there. Of course you can handle it with some async loading but this is not so easy.

**Comment by FilipMessa** [comment]
What about something like this?
```
<Button>
  <Icon name="remove">
   Remove booking
</Button>
```

**Comment by git-toni** [comment]
I think @FilipMessa 's suggestion allows us for a more flexible arrangement of the Button content(icon + label), but maybe that is not even desired as per design system?

Also, it's nice and minimalistic to have pre-defined icons that can be triggered only with a string... I'm still undecided on the fence : )

**Comment by Fallion** [comment]
I mean we could do simple checks with flow by exporting a list of all possible icons and setting that as a prop definition for icon names.

**Comment by darkwindcz** [comment]
@git-toni There will be very probably version with the button on the right side too, but I was thinking about solving this specifically, as the button on the right usually could be just some type of arrow (pointing down or right, etc.). But I didn't explore all possibilities yet so it's for the future.

About @FilipMessa' suggestion: won't it be hard for this to change the inner padding of a button if there is some icon inside? Also, it can lead us to situations when someone uses for example small icon in large button which shouldn't be even possible or use two icons in one button or whatever crazy combination we can imagine.

**Comment by Fallion** [comment]
@darkwindcz Padding is static, so the button would expand to accommodate the large Icon. However you can specifically style the Icon to be a specific style. This is one of the advantages of having the component as a Prop, you don't have to worry if all Icons will be correctly styled because you can style the Icon directly.

**Comment by git-toni** [comment]
I believe starting with @Fallion's suggestion of a flow check for icon names is a good start, see if we bump into a wall soon.

Regarding the padding I think @darkwindcz meant that you can maybe do:
`<Button size="large" icon={<CloseIcon size='small' />} />`, which shouldn't be allowed by design.

**Comment by darkwindcz** [comment]
@Fallion Just one thing about a padding - it's not a static value. Its size depends on the size of the button and if the button has icon or no. 

Not sure if there is something more I should add, the final decision which style to use is now on you guys. 👍
