### ISSUE TITLE
TAG component not passing event props when onRemove is called

### ISSUE THREAD

**Issue by caiodesign** [kiwicom/orbit-components#948]
Hi, I need to receive the props of the `onRemove` event when user clicks on the close button of Tag component. See the example in 'steps to reproduce'

## Expected Behavior

TAG `onRemove` should send EVENT props like `onClick` method.
example:
```javascript
removeTag = (event) => console.log(event.target.textContent) // myTag :)

<Tag selected onRemove={event => this.removeTag(event)}>
     myTag :)
</Tag>
```

## Current Behavior

Nothing is sent to callback. 
example:
```javascript
removeTag = (event) => console.log(event) // undefined

<Tag selected onRemove={event => this.removeTag(event)}>
     myTag :)
</Tag>
```

## Possible Solution

Change the TAB component to send event props when `onRemove` button is clicked or remove the feature and let the `onClick` do the job.

## Context (Environment)

I just need to receive the event props like `onClick` method.

**Comment by vepor** [comment]
I was trying to figure out a case where this is needed because for most cases you don't care about the event for `onRemove`, `onClose` etc.

Is this connected to the usage of Tags in InputField @caiodesign? It was the only case I figured out 🙂

**Comment by caiodesign** [comment]
Hello @vepor, Thank you for the supportt!! :)
