### ISSUE TITLE
<TripSegment> content breaks into next line and it looks confusing

### ISSUE THREAD

**Issue by tibor-kulcar** [kiwicom/orbit-components#974]
https://monosnap.com/file/y4kZIwzqLYu2YhvYc8kljJ7ISWs1gI

## Steps to Reproduce
for example: PRG-TOKYO
v
https://monosnap.com/file/y4kZIwzqLYu2YhvYc8kljJ7ISWs1gI

**Comment by vepor** [comment]
Fixed by #1160
