### ISSUE TITLE
Sticky flow definitions does not import React

### ISSUE THREAD

**Issue by prztrz** [kiwicom/orbit-components#975]
`src/Sticky/index.js.flow` file has `Props` definition including `children: React.Node` but it does not import React. How does it even pass your CI?

## Expected Behavior
Runing flow should pass without errors.

## Current Behavior
Got Error `Cannot resolve name React.` in abovementioned file when try to run flow in my project.

## Possible Solution
import React in abovementioned file.

**Comment by prztrz** [comment]
Hi @tomashapl thanks for fixing this, but  how is it possible that this passed your CI before?  This issue raises the question if you have other silent flow errors. Guess you guys should do some research on what happened that CI allowed this bug.

**Comment by tomashapl** [comment]
> Hi @tomashapl thanks for fixing this, but how is it possible that this passed your CI before? This issue raises the question if you have other silent flow errors. Guess you guys should do some research on what happened that CI allowed this bug.

Yes, for some reason it knows React even if you don't import it `¯\_(ツ)_/¯`, will investigate more, Thanks for report
